#!/usr/bin/env php
<?php

declare(strict_types=1);

// check if the "vendor" folder exists, if not, run "composer install"
if (! file_exists(__DIR__.'/vendor/autoload.php')) {
    shell_exec('composer install');
}
